import type { BrandProfile } from "./types";

/**
 * DEMO BrandProfile — used when ?preview=1 / NEXT_PUBLIC_PREVIEW_MODE=1.
 *
 * Mirrors the shape of a real scan output so every dashboard page renders
 * with realistic, non-empty data before auth is wired up. Values are drawn
 * from autoDSM's own design system so the preview feels on-brand.
 */
export const DEMO_REPO_SLUG = "sebmendo1/auto-dsm";

export const DEMO_BRAND_PROFILE: BrandProfile = {
  repo: {
    owner: "sebmendo1",
    name: "auto-dsm",
    branch: "brand-book-v1",
    url: "https://github.com/sebmendo1/auto-dsm",
  },
  scannedAt: "2026-04-22T20:00:00.000Z",
  scannedFromSha: "d1db382",

  // ── COLORS ────────────────────────────────────────────────────────────────
  colors: [
    {
      name: "primary",
      cssVariable: "--accent",
      value: "#8F23FA",
      hsl: "275 96% 56%",
      rgb: "rgb(143, 35, 250)",
      oklch: "oklch(0.54 0.28 294)",
      group: "brand",
      source: "globals.css:52",
      contrastOnWhite: 4.93,
      contrastOnBlack: 4.26,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: false,
    },
    {
      name: "primary-hover",
      cssVariable: "--accent-hover",
      value: "#AA56FF",
      hsl: "274 100% 67%",
      rgb: "rgb(170, 86, 255)",
      group: "brand",
      source: "globals.css:53",
      darkModeValue: "#AA56FF",
      darkModeHex: "#AA56FF",
      contrastOnWhite: 3.41,
      contrastOnBlack: 6.16,
      wcagAANormal: false,
      wcagAALarge: true,
      wcagAAA: false,
    },
    {
      name: "primary-pressed",
      cssVariable: "--accent-pressed",
      value: "#7A1DD6",
      hsl: "274 77% 48%",
      rgb: "rgb(122, 29, 214)",
      group: "brand",
      source: "globals.css:54",
      contrastOnWhite: 7.34,
      contrastOnBlack: 2.86,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: true,
    },
    {
      name: "success",
      cssVariable: "--success",
      value: "#22C55E",
      hsl: "142 71% 45%",
      rgb: "rgb(34, 197, 94)",
      group: "semantic",
      source: "globals.css:61",
      contrastOnWhite: 2.48,
      contrastOnBlack: 8.47,
      wcagAANormal: false,
      wcagAALarge: false,
      wcagAAA: false,
    },
    {
      name: "warning",
      cssVariable: "--warning",
      value: "#F59E0B",
      hsl: "38 92% 50%",
      rgb: "rgb(245, 158, 11)",
      group: "semantic",
      source: "globals.css:62",
      contrastOnWhite: 2.13,
      contrastOnBlack: 9.85,
      wcagAANormal: false,
      wcagAALarge: false,
      wcagAAA: false,
    },
    {
      name: "error",
      cssVariable: "--error",
      value: "#EF4444",
      hsl: "0 84% 60%",
      rgb: "rgb(239, 68, 68)",
      group: "semantic",
      source: "globals.css:63",
      contrastOnWhite: 3.76,
      contrastOnBlack: 5.58,
      wcagAANormal: false,
      wcagAALarge: true,
      wcagAAA: false,
    },
    {
      name: "bg-canvas",
      cssVariable: "--bg-canvas",
      value: "#0F0F11",
      hsl: "240 7% 6%",
      rgb: "rgb(15, 15, 17)",
      group: "surface",
      source: "globals.css:30",
      darkModeValue: "#0F0F11",
      darkModeHex: "#0F0F11",
      contrastOnWhite: 19.82,
      contrastOnBlack: 1.06,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: true,
    },
    {
      name: "bg-elevated",
      cssVariable: "--bg-elevated",
      value: "#141416",
      hsl: "240 4% 8%",
      rgb: "rgb(20, 20, 22)",
      group: "surface",
      source: "globals.css:31",
      contrastOnWhite: 18.34,
      contrastOnBlack: 1.15,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: true,
    },
    {
      name: "bg-secondary",
      cssVariable: "--bg-secondary",
      value: "#101012",
      hsl: "240 6% 7%",
      rgb: "rgb(16, 16, 18)",
      group: "surface",
      source: "globals.css:28",
      contrastOnWhite: 19.19,
      contrastOnBlack: 1.1,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: true,
    },
    {
      name: "text-primary",
      cssVariable: "--text-primary",
      value: "#F5F5F7",
      hsl: "240 9% 97%",
      rgb: "rgb(245, 245, 247)",
      group: "neutral",
      source: "globals.css:37",
      contrastOnWhite: 1.04,
      contrastOnBlack: 20.1,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: true,
    },
    {
      name: "text-secondary",
      cssVariable: "--text-secondary",
      value: "#A0A0A6",
      hsl: "240 4% 64%",
      rgb: "rgb(160, 160, 166)",
      group: "neutral",
      source: "globals.css:38",
      contrastOnWhite: 2.86,
      contrastOnBlack: 7.34,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: false,
    },
    {
      name: "border-default",
      cssVariable: "--border-default",
      value: "#232327",
      hsl: "240 4% 15%",
      rgb: "rgb(35, 35, 39)",
      group: "interactive",
      source: "globals.css:33",
      contrastOnWhite: 13.8,
      contrastOnBlack: 1.52,
      wcagAANormal: true,
      wcagAALarge: true,
      wcagAAA: true,
    },
  ],

  // ── TYPOGRAPHY ────────────────────────────────────────────────────────────
  typography: [
    {
      name: "display",
      fontFamily: "Manrope",
      fontSize: "3.25rem",
      fontSizePx: 52,
      fontWeight: "700",
      fontWeightNumeric: 700,
      lineHeight: "1.05",
      lineHeightPx: 55,
      letterSpacing: "-0.04em",
      source: "globals.css:140",
      category: "display",
      tailwindClass: "text-display",
    },
    {
      name: "h1",
      fontFamily: "Manrope",
      fontSize: "2.25rem",
      fontSizePx: 36,
      fontWeight: "700",
      fontWeightNumeric: 700,
      lineHeight: "1.15",
      lineHeightPx: 41,
      letterSpacing: "-0.025em",
      source: "globals.css:148",
      category: "heading",
      tailwindClass: "text-h1",
    },
    {
      name: "h2",
      fontFamily: "Manrope",
      fontSize: "1.5rem",
      fontSizePx: 24,
      fontWeight: "600",
      fontWeightNumeric: 600,
      lineHeight: "1.25",
      lineHeightPx: 30,
      letterSpacing: "-0.015em",
      source: "globals.css:156",
      category: "heading",
      tailwindClass: "text-h2",
    },
    {
      name: "h3",
      fontFamily: "Manrope",
      fontSize: "1.125rem",
      fontSizePx: 18,
      fontWeight: "600",
      fontWeightNumeric: 600,
      lineHeight: "1.35",
      lineHeightPx: 24,
      letterSpacing: "-0.01em",
      source: "globals.css:164",
      category: "heading",
      tailwindClass: "text-h3",
    },
    {
      name: "body",
      fontFamily: "Geist Sans",
      fontSize: "1rem",
      fontSizePx: 16,
      fontWeight: "400",
      fontWeightNumeric: 400,
      lineHeight: "1.55",
      lineHeightPx: 25,
      source: "globals.css:172",
      category: "body",
      tailwindClass: "text-body",
    },
    {
      name: "body-s",
      fontFamily: "Geist Sans",
      fontSize: "0.875rem",
      fontSizePx: 14,
      fontWeight: "400",
      fontWeightNumeric: 400,
      lineHeight: "1.5",
      lineHeightPx: 21,
      source: "globals.css:179",
      category: "body",
      tailwindClass: "text-body-s",
    },
    {
      name: "caption",
      fontFamily: "Geist Sans",
      fontSize: "0.75rem",
      fontSizePx: 12,
      fontWeight: "500",
      fontWeightNumeric: 500,
      lineHeight: "1.4",
      lineHeightPx: 17,
      letterSpacing: "0.01em",
      source: "globals.css:186",
      category: "utility",
      tailwindClass: "text-caption",
    },
    {
      name: "code",
      fontFamily: "Geist Mono",
      fontSize: "0.8125rem",
      fontSizePx: 13,
      fontWeight: "400",
      fontWeightNumeric: 400,
      lineHeight: "1.5",
      lineHeightPx: 20,
      source: "globals.css:193",
      category: "utility",
      tailwindClass: "text-code",
    },
  ],
  fonts: [
    {
      family: "Manrope",
      importMethod: "next/font/google",
      source: "app/layout.tsx:12",
      weights: [
        { value: "500", name: "Medium" },
        { value: "600", name: "Semibold" },
        { value: "700", name: "Bold" },
      ],
      styles: ["normal"],
      variable: "--font-manrope",
      fallbacks: ["ui-sans-serif", "system-ui", "sans-serif"],
      subsets: ["latin"],
      displayStrategy: "swap",
      role: "display",
    },
    {
      family: "Geist Sans",
      importMethod: "geist",
      source: "app/layout.tsx:14",
      weights: [
        { value: "400", name: "Regular" },
        { value: "500", name: "Medium" },
        { value: "600", name: "Semibold" },
      ],
      styles: ["normal"],
      variable: "--font-geist-sans",
      fallbacks: ["ui-sans-serif", "system-ui", "sans-serif"],
      subsets: ["latin"],
      displayStrategy: "swap",
      role: "primary",
    },
    {
      family: "Geist Mono",
      importMethod: "geist",
      source: "app/layout.tsx:15",
      weights: [{ value: "400", name: "Regular" }],
      styles: ["normal"],
      variable: "--font-geist-mono",
      fallbacks: ["ui-monospace", "SFMono-Regular", "monospace"],
      subsets: ["latin"],
      displayStrategy: "swap",
      role: "code",
    },
  ],

  // ── SPACING ───────────────────────────────────────────────────────────────
  spacing: [
    { name: "0", tailwindClass: "p-0", rem: "0rem", px: 0, source: "tailwind default", isCustom: false },
    { name: "1", tailwindClass: "p-1", rem: "0.25rem", px: 4, source: "tailwind default", isCustom: false },
    { name: "2", tailwindClass: "p-2", rem: "0.5rem", px: 8, source: "tailwind default", isCustom: false },
    { name: "3", tailwindClass: "p-3", rem: "0.75rem", px: 12, source: "tailwind default", isCustom: false },
    { name: "4", tailwindClass: "p-4", rem: "1rem", px: 16, source: "tailwind default", isCustom: false },
    { name: "5", tailwindClass: "p-5", rem: "1.25rem", px: 20, source: "tailwind default", isCustom: false },
    { name: "6", tailwindClass: "p-6", rem: "1.5rem", px: 24, source: "tailwind default", isCustom: false },
    { name: "8", tailwindClass: "p-8", rem: "2rem", px: 32, source: "tailwind default", isCustom: false },
    { name: "10", tailwindClass: "p-10", rem: "2.5rem", px: 40, source: "tailwind default", isCustom: false },
    { name: "12", tailwindClass: "p-12", rem: "3rem", px: 48, source: "tailwind default", isCustom: false },
    { name: "14", tailwindClass: "p-14", rem: "3.5rem", px: 56, source: "globals.css:88", isCustom: true },
  ],

  // ── SHADOWS ───────────────────────────────────────────────────────────────
  shadows: [
    {
      name: "shadow-xs",
      tailwindClass: "shadow-xs",
      value: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      layers: [
        { offsetX: "0", offsetY: "1px", blur: "2px", spread: "0", color: "rgb(0 0 0 / 0.05)", colorHex: "#0000000D", inset: false },
      ],
      source: "tailwind default",
      isCustom: false,
    },
    {
      name: "shadow-sm",
      tailwindClass: "shadow-sm",
      value: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      layers: [
        { offsetX: "0", offsetY: "1px", blur: "3px", spread: "0", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
        { offsetX: "0", offsetY: "1px", blur: "2px", spread: "-1px", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
      ],
      source: "tailwind default",
      isCustom: false,
    },
    {
      name: "shadow-md",
      tailwindClass: "shadow-md",
      value: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      layers: [
        { offsetX: "0", offsetY: "4px", blur: "6px", spread: "-1px", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
        { offsetX: "0", offsetY: "2px", blur: "4px", spread: "-2px", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
      ],
      source: "tailwind default",
      isCustom: false,
    },
    {
      name: "shadow-lg",
      tailwindClass: "shadow-lg",
      value: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      layers: [
        { offsetX: "0", offsetY: "10px", blur: "15px", spread: "-3px", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
        { offsetX: "0", offsetY: "4px", blur: "6px", spread: "-4px", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
      ],
      source: "tailwind default",
      isCustom: false,
    },
    {
      name: "shadow-xl",
      tailwindClass: "shadow-xl",
      value: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      layers: [
        { offsetX: "0", offsetY: "20px", blur: "25px", spread: "-5px", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
        { offsetX: "0", offsetY: "8px", blur: "10px", spread: "-6px", color: "rgb(0 0 0 / 0.1)", colorHex: "#0000001A", inset: false },
      ],
      source: "tailwind default",
      isCustom: false,
    },
    {
      name: "shadow-focus",
      tailwindClass: "shadow-focus",
      value: "0 0 0 3px rgb(143 35 250 / 0.4)",
      layers: [
        { offsetX: "0", offsetY: "0", blur: "0", spread: "3px", color: "rgb(143 35 250 / 0.4)", colorHex: "#8F23FA66", inset: false },
      ],
      source: "globals.css:108",
      isCustom: true,
    },
  ],

  // ── RADII ─────────────────────────────────────────────────────────────────
  radii: [
    { name: "none", tailwindClass: "rounded-none", value: "0px", px: 0, source: "tailwind default", isCustom: false },
    { name: "sm", tailwindClass: "rounded-sm", value: "4px", px: 4, source: "tailwind default", isCustom: false },
    { name: "md", tailwindClass: "rounded-md", value: "6px", px: 6, source: "tailwind default", isCustom: false },
    { name: "lg", tailwindClass: "rounded-lg", value: "8px", px: 8, cssVariable: "--radius-button", source: "globals.css:96", isCustom: false },
    { name: "xl", tailwindClass: "rounded-xl", value: "12px", px: 12, cssVariable: "--radius-card", source: "globals.css:97", isCustom: false },
    { name: "2xl", tailwindClass: "rounded-2xl", value: "16px", px: 16, cssVariable: "--radius-modal", source: "globals.css:98", isCustom: false },
    { name: "full", tailwindClass: "rounded-full", value: "9999px", px: 9999, source: "tailwind default", isCustom: false },
  ],

  // ── BORDERS ───────────────────────────────────────────────────────────────
  borders: [
    { name: "border-subtle", width: "1px", style: "solid", color: "#1B1B1E", colorToken: "--border-subtle", source: "globals.css:34" },
    { name: "border-default", width: "1px", style: "solid", color: "#232327", colorToken: "--border-default", source: "globals.css:33" },
    { name: "border-strong", width: "1px", style: "solid", color: "#2D2D32", colorToken: "--border-strong", source: "globals.css:35" },
    { name: "border-accent", width: "1px", style: "solid", color: "#8F23FA", colorToken: "--accent", source: "components/button.tsx:22" },
    { name: "border-dashed", width: "1px", style: "dashed", color: "#2D2D32", colorToken: "--border-strong", source: "components/empty-state.tsx:18" },
    { name: "border-focus", width: "2px", style: "solid", color: "#8F23FA", colorToken: "--accent", source: "globals.css:112" },
  ],

  // ── ANIMATIONS ────────────────────────────────────────────────────────────
  animations: [
    {
      name: "fade-in",
      type: "keyframes",
      tailwindClass: "animate-fade-in",
      duration: "150ms",
      timingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
      keyframes: "@keyframes fade-in { from { opacity: 0 } to { opacity: 1 } }",
      source: "globals.css:215",
      isCustom: true,
    },
    {
      name: "slide-in-up",
      type: "keyframes",
      tailwindClass: "animate-slide-in-up",
      duration: "200ms",
      timingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
      keyframes: "@keyframes slide-in-up { from { transform: translateY(8px); opacity: 0 } to { transform: translateY(0); opacity: 1 } }",
      source: "globals.css:220",
      isCustom: true,
    },
    {
      name: "pulse",
      type: "keyframes",
      tailwindClass: "animate-pulse",
      duration: "2s",
      timingFunction: "cubic-bezier(0.4, 0, 0.6, 1)",
      delay: "0s",
      source: "tailwind default",
      isCustom: false,
    },
    {
      name: "transition-colors",
      type: "transition",
      tailwindClass: "transition-colors",
      duration: "150ms",
      timingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
      source: "globals.css:110",
      isCustom: false,
    },
    {
      name: "transition-transform",
      type: "transition",
      duration: "200ms",
      timingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
      source: "components/sidebar.tsx:44",
      isCustom: false,
    },
  ],

  // ── BREAKPOINTS ───────────────────────────────────────────────────────────
  breakpoints: [
    { name: "sm", value: "640px", px: 640, source: "tailwind default", isCustom: false },
    { name: "md", value: "768px", px: 768, source: "tailwind default", isCustom: false },
    { name: "lg", value: "1024px", px: 1024, source: "tailwind default", isCustom: false },
    { name: "xl", value: "1280px", px: 1280, source: "tailwind default", isCustom: false },
    { name: "2xl", value: "1536px", px: 1536, source: "tailwind default", isCustom: false },
  ],

  // ── OPACITY ───────────────────────────────────────────────────────────────
  opacity: [
    { name: "0", value: 0, percentage: "0%", source: "tailwind default", isCustom: false },
    { name: "5", value: 0.05, percentage: "5%", source: "tailwind default", isCustom: false },
    { name: "10", value: 0.1, percentage: "10%", source: "tailwind default", isCustom: false },
    { name: "20", value: 0.2, percentage: "20%", source: "tailwind default", isCustom: false },
    { name: "40", value: 0.4, percentage: "40%", source: "tailwind default", isCustom: false },
    { name: "60", value: 0.6, percentage: "60%", source: "tailwind default", isCustom: false },
    { name: "80", value: 0.8, percentage: "80%", source: "tailwind default", isCustom: false },
    { name: "100", value: 1, percentage: "100%", source: "tailwind default", isCustom: false },
  ],

  // ── Z-INDEX ───────────────────────────────────────────────────────────────
  zIndex: [
    { name: "base", value: 0, tailwindClass: "z-0", source: "tailwind default", isCustom: false, inferredRole: "Page content" },
    { name: "dropdown", value: 10, tailwindClass: "z-10", source: "components/dropdown.tsx:12", isCustom: false, inferredRole: "Dropdown menus, popovers" },
    { name: "sticky", value: 20, tailwindClass: "z-20", source: "components/sticky-nav.tsx:8", isCustom: false, inferredRole: "Sticky navigation" },
    { name: "overlay", value: 40, tailwindClass: "z-40", source: "components/overlay.tsx:14", isCustom: false, inferredRole: "Backdrop overlays" },
    { name: "modal", value: 50, tailwindClass: "z-50", source: "components/modal.tsx:22", isCustom: false, inferredRole: "Modals, dialogs" },
    { name: "toast", value: 60, tailwindClass: "z-60", source: "globals.css:116", isCustom: true, inferredRole: "Toasts, notifications" },
  ],

  // ── GRADIENTS ─────────────────────────────────────────────────────────────
  gradients: [
    {
      name: "brand-gradient",
      type: "linear",
      cssValue: "linear-gradient(135deg, #8F23FA 0%, #AA56FF 100%)",
      stops: [
        { color: "rgb(143, 35, 250)", colorHex: "#8F23FA", position: "0%", tokenRef: "--accent" },
        { color: "rgb(170, 86, 255)", colorHex: "#AA56FF", position: "100%", tokenRef: "--accent-hover" },
      ],
      direction: "135deg",
      source: "globals.css:122",
    },
    {
      name: "surface-glow",
      type: "radial",
      cssValue: "radial-gradient(circle at 50% 0%, rgba(143, 35, 250, 0.22), transparent 70%)",
      stops: [
        { color: "rgba(143, 35, 250, 0.22)", colorHex: "#8F23FA38", position: "0%" },
        { color: "transparent", colorHex: "#00000000", position: "70%" },
      ],
      direction: "circle at 50% 0%",
      source: "components/hero.tsx:42",
    },
    {
      name: "subtle-fade",
      type: "linear",
      cssValue: "linear-gradient(180deg, #141416 0%, #0F0F11 100%)",
      stops: [
        { color: "rgb(20, 20, 22)", colorHex: "#141416", position: "0%", tokenRef: "--bg-elevated" },
        { color: "rgb(15, 15, 17)", colorHex: "#0F0F11", position: "100%", tokenRef: "--bg-canvas" },
      ],
      direction: "180deg",
      source: "globals.css:128",
    },
    {
      name: "accent-ring",
      type: "conic",
      cssValue: "conic-gradient(from 90deg, #8F23FA, #AA56FF, #7A1DD6, #8F23FA)",
      stops: [
        { color: "rgb(143, 35, 250)", colorHex: "#8F23FA" },
        { color: "rgb(170, 86, 255)", colorHex: "#AA56FF" },
        { color: "rgb(122, 29, 214)", colorHex: "#7A1DD6" },
        { color: "rgb(143, 35, 250)", colorHex: "#8F23FA" },
      ],
      direction: "from 90deg",
      source: "components/avatar-ring.tsx:18",
    },
  ],

  // ── ASSETS ────────────────────────────────────────────────────────────────
  assets: [
    {
      name: "autodsm-icon-light",
      path: "public/brand/autodsm-icon-light.svg",
      type: "svg",
      category: "logo",
      fileSize: 1240,
      fileSizeFormatted: "1.2 KB",
      dimensions: { width: 40, height: 40 },
      hasTransparency: true,
      content: `<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="demo-g1" x1="0" y1="0" x2="40" y2="40" gradientUnits="userSpaceOnUse"><stop stop-color="#8F23FA"/><stop offset="1" stop-color="#AA56FF"/></linearGradient></defs><path d="M20 2L35.32 11V29L20 38L4.68 29V11L20 2Z" fill="url(#demo-g1)"/><path d="M13 26V14L20 18L27 14V26" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    },
    {
      name: "autodsm-wordmark-light",
      path: "public/brand/autodsm-wordmark-light.svg",
      type: "svg",
      category: "logo",
      fileSize: 2180,
      fileSizeFormatted: "2.1 KB",
      dimensions: { width: 148, height: 28 },
      hasTransparency: true,
      content: `<svg width="148" height="28" viewBox="0 0 148 28" fill="none" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="demo-g2" x1="0" y1="0" x2="28" y2="28" gradientUnits="userSpaceOnUse"><stop stop-color="#8F23FA"/><stop offset="1" stop-color="#AA56FF"/></linearGradient></defs><path d="M14 1.4L24.72 7.7V20.3L14 26.6L3.28 20.3V7.7L14 1.4Z" fill="url(#demo-g2)"/><path d="M9 18V10L14 13L19 10V18" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><text x="34" y="19" font-family="Manrope, sans-serif" font-size="16" font-weight="700" fill="#111113">autoDSM</text></svg>`,
    },
    {
      name: "favicon",
      path: "public/favicon.ico",
      type: "ico",
      category: "favicon",
      fileSize: 3840,
      fileSizeFormatted: "3.8 KB",
      dimensions: { width: 32, height: 32 },
      hasTransparency: true,
    },
    {
      name: "icon-sparkles",
      path: "public/icons/sparkles.svg",
      type: "svg",
      category: "icon",
      fileSize: 520,
      fileSizeFormatted: "520 B",
      dimensions: { width: 24, height: 24 },
      hasTransparency: true,
      content: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#8F23FA" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" xmlns="http://www.w3.org/2000/svg"><path d="m12 3-1.9 5.8a2 2 0 0 1-1.3 1.3L3 12l5.8 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.8a2 2 0 0 1 1.3-1.3L21 12l-5.8-1.9a2 2 0 0 1-1.3-1.3L12 3Z"/></svg>`,
    },
    {
      name: "icon-check",
      path: "public/icons/check.svg",
      type: "svg",
      category: "icon",
      fileSize: 320,
      fileSizeFormatted: "320 B",
      dimensions: { width: 24, height: 24 },
      hasTransparency: true,
      content: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#22C55E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" xmlns="http://www.w3.org/2000/svg"><path d="M20 6 9 17l-5-5"/></svg>`,
    },
    {
      name: "illustration-brand-book",
      path: "public/illustrations/brand-book.svg",
      type: "svg",
      category: "illustration",
      fileSize: 4820,
      fileSizeFormatted: "4.8 KB",
      dimensions: { width: 320, height: 200 },
      hasTransparency: true,
      content: `<svg width="320" height="200" viewBox="0 0 320 200" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="40" y="30" width="240" height="140" rx="12" fill="#141416" stroke="#232327"/><circle cx="80" cy="70" r="18" fill="#8F23FA"/><rect x="110" y="60" width="140" height="8" rx="4" fill="#232327"/><rect x="110" y="76" width="90" height="6" rx="3" fill="#1B1B1E"/><rect x="60" y="110" width="200" height="40" rx="8" fill="#17171A" stroke="#232327"/></svg>`,
    },
    {
      name: "illustration-empty-state",
      path: "public/illustrations/empty-state.svg",
      type: "svg",
      category: "illustration",
      fileSize: 2940,
      fileSizeFormatted: "2.9 KB",
      dimensions: { width: 240, height: 160 },
      hasTransparency: true,
      content: `<svg width="240" height="160" viewBox="0 0 240 160" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="60" y="30" width="120" height="100" rx="8" fill="none" stroke="#2D2D32" stroke-width="1.5" stroke-dasharray="4 4"/><circle cx="120" cy="80" r="24" fill="#1B1B1E" stroke="#232327"/><path d="M108 80 L118 90 L132 72" stroke="#8F23FA" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    },
  ],

  // ── META ──────────────────────────────────────────────────────────────────
  meta: {
    filesScanned: 127,
    cssSource: "src/app/globals.css",
    tailwindConfigPath: "tailwind.config.ts",
    shadcnConfigPath: "components.json",
    tailwindVersion: "4",
  },
};
